#!/bin/bash
# Remove previous code.
rm -rf /root/.terraform*
rm -rf /root/terraform*
rm /root/*.tf

# Create new resources.
cat <<EOF > certificate.tf
resource "tls_private_key" "key" {
  algorithm = "ECDSA"
}

resource "tls_self_signed_cert" "certificate" {
  key_algorithm   = "\${tls_private_key.key.algorithm}"
  private_key_pem = "\${tls_private_key.key.private_key_pem}"

  validity_period_hours = 12

  early_renewal_hours = 3

  allowed_uses = [
      "key_encipherment",
      "digital_signature",
      "server_auth"
  ]

  dns_names = ["instruqt.com", "instruqt.io"]

  subject {
      common_name  = "instruqt.com"
      organization = "instruqt"
  }
}
EOF

# Initialize and apply the changes.
terraform init
terraform apply -auto-approve

exit 0